FROM php:7.2-fpm

RUN apt-get update && apt-get -y install git

RUN apt-get install -y \
        libzip-dev \
        zip \
    && docker-php-ext-configure zip --with-libzip \
    && docker-php-ext-install zip

WORKDIR /var/www

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN git clone https://github.com/duvanmanzano/100deCilantro.git

WORKDIR /var/www/100deCilantro

RUN chown -R www-data:www-data \
        /var/www/100deCilantro/storage \
        /var/www/100deCilantro/bootstrap/cache

RUN  apt-get install -y libmcrypt-dev \
        libmagickwand-dev --no-install-recommends \
        && pecl install mcrypt-1.0.2 \
        && docker-php-ext-install pdo_mysql \
        && docker-php-ext-enable mcrypt

RUN composer install

RUN mv .env.prod .env

VOLUME ["/volume"]